FROM mcr.microsoft.com/openjdk/jdk:11-ubuntu

RUN apt-get update && \
    apt-get install -y python3 python3-pip   && \
    rm -rf /var/lib/apt/lists/*


RUN pip3 install pyspark==3.5.0 

WORKDIR /app

COPY streamingYTComments.py /app/
COPY /jars/postgresql-42.7.3.jar /app/jars/
COPY /jars/aws-java-sdk-bundle-1.12.262.jar /app/jars/
COPY /jars/hadoop-aws-3.3.1.jar /app/jars/
COPY /jars/spark-sql-kafka-0-10_2.12-3.5.0.jar /app/jars/
COPY /jars/kafka-clients-3.4.1.jar /app/jars/
COPY /jars/commons-pool2-2.11.1.jar /app/jars/
COPY /jars/spark-token-provider-kafka-0-10_2.12-3.5.0.jar /app/jars/

CMD ["spark-submit",\
     "--master", "spark://spark-master-stream:7077",\
     "--jars", "/app/jars/postgresql-42.7.3.jar,/app/jars/spark-sql-kafka-0-10_2.12-3.5.0.jar,/app/jars/kafka-clients-3.4.1.jar,/app/jars/commons-pool2-2.11.1.jar,/app/jars/spark-token-provider-kafka-0-10_2.12-3.5.0.jar",\
     "/app/streamingYTComments.py"]

