FROM mcr.microsoft.com/openjdk/jdk:11-ubuntu

RUN apt-get update && \
    apt-get install -y python3 python3-pip cron bsdmainutils && \
    rm -rf /var/lib/apt/lists/*


RUN pip3 install pyspark==3.5.0 boto3

WORKDIR /app

COPY /jsonConvertToSpark.py /app/
COPY /jars/postgresql-42.7.3.jar /app/
COPY /jars/aws-java-sdk-bundle-1.12.262.jar /app/
COPY /jars/hadoop-aws-3.3.1.jar /app/


COPY run_spark.sh /app/
COPY crontab /etc/cron.d/spark-cron

RUN chmod +x /app/run_spark.sh
RUN chmod 0644 /etc/cron.d/spark-cron

RUN crontab /etc/cron.d/spark-cron

# Pokreni cron u foreground
CMD ["cron", "-f"]